name: Apply Terraform Changes

on:
  push:
    branches:
      - 'main'
    paths:
      - 'main/**/*.tf'
      - '.github/workflows/apply.yml'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  TF_ROOT: ./main

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR SHA from Merge Commit
        id: get-pr-sha
        run: |
          PR_SHA=$(git log -1 --pretty=format:%P ${{ github.sha }} | awk '{print $1}')
          echo "pr_sha=${PR_SHA}" >> $GITHUB_OUTPUT

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-${{ steps.get-pr-sha.outputs.pr_sha }}

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init
        
      - name: Apply Terraform
        run: terraform apply -auto-approve plans/plan_${{ steps.get-pr-sha.outputs.pr_sha }}.tfplan
