name: Terraform Apply

on:
  push:
    branches:
      - 'main'
    paths:
      - 'main/**/*.tf'
      - '.github/workflows/terraform-apply.yml'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  TF_ROOT: ./main

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TF_ROOT }}
        run: |
          plan_file="${{ github.sha }}.plan"
          terraform plan \
            -var="github_project_url=https://github.com/${{ github.repository }}" \
            -out=$plan_file
          terraform show -no-color $plan_file > ${plan_file}.txt
          echo "plan_file=${plan_file}" >> $GITHUB_OUTPUT
          echo "plan_file_txt=${plan_file}.txt" >> $GITHUB_OUTPUT
          
      - name: Upload Plan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ github.sha }}
          path: |
            ${{ env.TF_ROOT }}/${{ github.sha }}.plan
            ${{ env.TF_ROOT }}/${{ github.sha }}.plan.txt
          retention-days: 1

  apply:
    name: Terraform Apply
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan-${{ github.sha }}
          path: ${{ env.TF_ROOT }}/

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init -input=false

      - name: Terraform Apply
        working-directory: ${{ env.TF_ROOT }}
        run: terraform apply -input=false -auto-approve ${{ github.sha }}.plan